package com.yashen.wms.util;

public enum Routes {
    MAIN_FORM,ADMIN_MAIN_FORM,ADMIN_BUSINESS_FUNCTIONS,CUSTOMER,
    ADD_CUSTOMER,VIEW_CUSTOMER,SEARCH_CUSTOMERS,
    ORDERS, MAKE_ORDER , PLACE_ORDER , VIEW_ORDERS,
    INERNAL_MAIN_VIEW,PRODUCTS_MAIN_VIEW,ADD_NEW_PRODUCT,VIEW_PRODUCT,
    STORE_MAIN_VIEW,STORE_CRUD,MANAGE_STORE_QTY,
    ACC_MAIN,SIGN_UP,ACC_UPDATE
}
